
class XLConfig:
    
    ADDRESS_ID                  = 7
    ADDRESS_BAUDRATE            = 8
    ADDRESS_OPERATING_MODE      = 11
    ADDRESS_VELOCITY_LIMIT      = 44
    ADDRESS_MAX_POSITION_LIMIT  = 48
    ADDRESS_MIN_POSITION_LIMIT  = 52
    ADDRESS_TORQUE_ENABLE       = 64
    ADDRESS_LED                 = 65
    ADDRESS_GOAL_VELOCITY       = 104
    ADDRESS_GOAL_POSITION       = 116
    ADDRESS_PRESENT_POSITION    = 132


    OPERATING_MODE_VELOCITY_CONTROL_MODE = 1
    OPERATING_MODE_POSITION_CONTROL_MODE = 3


    


    MAXIMUM_POSITION_VALUE          = 4096

